# Generated by Django 2.0.1 on 2018-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_auto_20180121_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('date', models.IntegerField(default=0)),
                ('itemid', models.BigIntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
